
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.93.125.10:3306/video
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://admin:123456@47.93.125.10:27017/video


  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 47.93.125.10
    port: 5672
    username: admin
    password: 123456

server:
  port: 8072



video:
  path: /Users/genghaoran/myVideos/
  transcodePath: /Users/genghaoran/transcodeVideos/
  dash-path: /Users/genghaoran/dashVideos/
